package ex.neskoro.rotor;

// reference - https://en.wikipedia.org/wiki/Enigma_rotor_details
public enum StandardRotorType {
    I_C("DMTWSILRUYQNKFEJCAZBPGXOHV"),
    II_C("HQZGPJTMOBLNCIFDYAWVEUSRKX"),
    III_C("UQNTLSZFMREHDPXKIBVYGJCWOA"),

    I_GR("JGDQOXUSCAMIFRVTPNEWKBLZYH"),
    II_GR("NTZPSFBOKMWRCJDIVLAEYUXHGQ"),
    III_GR("JVIUBHTCDYAKEQZPOSGXNRMWFL"),
//    UKW_GR("QYHOGNECVPUZTFDJAXWMKISRBL", RotorType.REFLECTOR),
//    ETW_GR("QWERTZUIOASDFGHJKPYXCVBNML", RotorType.ENTRY_ROTOR),

    I_K("PEZUOHXSCVFMTBGLRINQJWAYDK"),
    II_K("ZOUESYDKFWPCIQXHMVBLGNJRAT"),
    III_K("EHRVXGAOBQUSIMZFLYNWKTPDJC"),
//    UKW_K("IMETCGFRAYSQBZXWLHKDVUPOJN", RotorType.REFLECTOR),
//    ETW_K("QWERTZUIOASDFGHJKPYXCVBNML", RotorType.ENTRY_ROTOR),

    I("EKMFLGDQVZNTOWYHXUSPAIBRCJ"),
    II("EKMFLGDQVZNTOWYHXUSPAIBRCJ"),
    III("BDFHJLCPRTXVZNYEIWGAKMUSQO"),
    IV("ESOVPZJAYQUIRHXLNFTGKDCMWB"),
    V("VZBRGITYUPSDNHLXAWMJQOFECK"),
    VI("JPGVOUMFYQBENHZRDKASXLICTW"),
    VII("NZJHGRCXMYSWBOUFAIVLPEKQDT"),
    VIII("FKQHTLXOCBJSPDZRAMEWNIUYGV"),

    BETA("LEYJVCNIXWPBQMDRTAKZGFUHOS"),
    GAMMA("FSOKANUERHMBTIYCWLQPZXVGJD"),
//    REFLECTOR_A("EJMZALYXVBWFCRQUONTSPIKHGD", RotorType.REFLECTOR),
//    REFLECTOR_B("YRUHQSLDPXNGOKMIEBFZCWVJAT", RotorType.REFLECTOR),
//    REFLECTOR_C("FVPJIAOYEDRZXWGCTKUQSBNMHL", RotorType.REFLECTOR),
//    REFLECTOR_B_THIN("ENKQAUYWJICOPBLMDXZVFTHRGS", RotorType.REFLECTOR),
//    REFLECTOR_C_THIN("RDOBJNTKVEHMLFCWZAXGYIPSUQ", RotorType.REFLECTOR),
    // one to one
//    ETW_E_I("ABCDEFGHIJKLMNOPQRSTUVWXYZ", RotorType.ENTRY_ROTOR),
    ;

    public final String movableListState;

    StandardRotorType(String str) {
        movableListState = str.toLowerCase();
    }
}
