package ex.neskoro.rotor;

// reference - https://en.wikipedia.org/wiki/Enigma_rotor_details
public enum StandardRotorType {
    I_C("DMTWSILRUYQNKFEJCAZBPGXOHV", "A"),
    II_C("HQZGPJTMOBLNCIFDYAWVEUSRKX", "A"),
    III_C("UQNTLSZFMREHDPXKIBVYGJCWOA", "A"),

    I_GR("JGDQOXUSCAMIFRVTPNEWKBLZYH", "N"),
    II_GR("NTZPSFBOKMWRCJDIVLAEYUXHGQ", "E"),
    III_GR("JVIUBHTCDYAKEQZPOSGXNRMWFL", "Y"),
//    UKW_GR("QYHOGNECVPUZTFDJAXWMKISRBL", RotorType.REFLECTOR),
//    ETW_GR("QWERTZUIOASDFGHJKPYXCVBNML", RotorType.ENTRY_ROTOR),

    I_K("PEZUOHXSCVFMTBGLRINQJWAYDK", "Y"),
    II_K("ZOUESYDKFWPCIQXHMVBLGNJRAT", "E"),
    III_K("EHRVXGAOBQUSIMZFLYNWKTPDJC", "N"),
//    UKW_K("IMETCGFRAYSQBZXWLHKDVUPOJN", RotorType.REFLECTOR),
//    ETW_K("QWERTZUIOASDFGHJKPYXCVBNML", RotorType.ENTRY_ROTOR),

    I("EKMFLGDQVZNTOWYHXUSPAIBRCJ", "Q"),
    II("EKMFLGDQVZNTOWYHXUSPAIBRCJ", "E"),
    III("BDFHJLCPRTXVZNYEIWGAKMUSQO", "V"),
    IV("ESOVPZJAYQUIRHXLNFTGKDCMWB", "J"),
    V("VZBRGITYUPSDNHLXAWMJQOFECK", "Z"),
    VI("JPGVOUMFYQBENHZRDKASXLICTW", "ZM"),
    VII("NZJHGRCXMYSWBOUFAIVLPEKQDT", "ZM"),
    VIII("FKQHTLXOCBJSPDZRAMEWNIUYGV", "ZM"),

//    BETA("LEYJVCNIXWPBQMDRTAKZGFUHOS", RotorType.ENTRY_ROTOR),
//    GAMMA("FSOKANUERHMBTIYCWLQPZXVGJD", RotorType.ENTRY_ROTOR),
//    REFLECTOR_A("EJMZALYXVBWFCRQUONTSPIKHGD", RotorType.REFLECTOR),
//    REFLECTOR_B("YRUHQSLDPXNGOKMIEBFZCWVJAT", RotorType.REFLECTOR),
//    REFLECTOR_C("FVPJIAOYEDRZXWGCTKUQSBNMHL", RotorType.REFLECTOR),
//    REFLECTOR_B_THIN("ENKQAUYWJICOPBLMDXZVFTHRGS", RotorType.REFLECTOR),
//    REFLECTOR_C_THIN("RDOBJNTKVEHMLFCWZAXGYIPSUQ", RotorType.REFLECTOR),
    // one to one
//    ETW_E_I("ABCDEFGHIJKLMNOPQRSTUVWXYZ", RotorType.ENTRY_ROTOR),
    ;

    public final String movableListState;
    public final String turnoverState;

    StandardRotorType(String listState, String turnoverState) {
        movableListState = listState.toLowerCase();
        this.turnoverState = turnoverState.toLowerCase();
    }
}
